apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pi
spec:
  slotsPerWorker: 1
  runPolicy:
    # cleanPodPolicy: Running
    # ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          securityContext:
            fsGroup: 1000
          containers:
          - image: kubeflow/mpi-pi
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - mpirun
            args:
            - -n
            - "2"
            - /opt/mpi/pi
            resources:
              limits:
                cpu: 1
                memory: 1Gi
    Worker:
      replicas: 2
      template:
        spec:
          securityContext:
            fsGroup: 1000
          containers:
          - image: kubeflow/mpi-pi
            name: mpi-worker
            securityContext:
              runAsUser: 1000
              capabilities:
                add:
                - NET_BIND_SERVICE
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /opt/ssh/sshd_config
            resources:
              limits:
                cpu: 1
                memory: 1Gi
